### ISSUE TITLE
Update for Big Sur

### ISSUE THREAD

**Issue by winkelsdorf** [SteveBarnegren/XcodeCommentWrapper#6]
Hello Steve,

thanks for this great product. I saw that you updated it recently after my Review in the MAS. Thanks for that!

Unfortunately it still didn't work with Xcode 12 on Big Sur. This is due to XcodeKit.framework requiring now to be embedded & signed in the extension to work (saw that in the debugger output). I found a comparable issue here, where the Apple release notes for Xcode 12 are attached: https://github.com/fespinoza/HelloXcodeExtensions/commit/ad4bf5305e1edecd887b9616375e7580a33295fa.

I decided to create a fork and if you like have a look at my PR.

It fixes the embedding, fixes Dark Mode text colors on macOS and adjust minor things I noticed to better reflect the current Xcode defaults.

Now it works as it should :)

See linked PR.

hth!

All the best
Frederik

**Comment by SteveBarnegren** [comment]
Hi Frederik,

Thanks so much for taking the time to fix this! The last update was working from a local build for me, but unfortunately as you noticed it still didn't show up in Xcode from the MAS.

Thanks for the other improvements too. I'm keen to get this working again, so I'll check this out your PR, give it a test, and hopefully get a new build submitted this weekend. 👍

**Comment by winkelsdorf** [comment]
Hi Steve,

you're very welcome! Yea, that's what I thought, was bit tricky to find out what was eventually missing (the embedding). Sure, take your time, let me know if you have any questions why I changed something.

All the best
Frederik

**Comment by winkelsdorf** [comment]
Closing as PR #7 had been merged.

**Comment by SteveBarnegren** [comment]
Fixed in version [1.0.2](https://github.com/SteveBarnegren/XcodeCommentWrapper/releases/tag/1.0.2)

Submitted to the mac app store for review.
